trigger:
  branches:
    include:
      - master
  tags:
    include:
      - v*

resources:
- repo: self

stages:
- stage: Deployment
  displayName: Deployment
  jobs:
  - job: Deployment
    displayName: Deployment on integration
    pool:
      vmImage: 'ubuntu-latest'
    steps:
    - task: ShellScript@2
      displayName: Build helm application
      inputs:
        scriptPath: build.sh
    - bash: |
        TOKEN=$(githubToken)
        git config user.email "contact@cenotelie.fr"
        git config user.name "Azure Pipeline"
        git add .
        git commit -m "Packaged new version"
        git push https://%TOKEN%@github.com/cenotelie/ecollab-helm
    # - task: SSH@0
    #   inputs:
    #     sshEndpoint: ecollab-integration
    #     runOptions: 'commands'
    #     commands: |
    #       sudo helm repo update
    #       sudo helm upgrade `sudo helm list | awk /ecollab/'{ print $1 }'` ecollab/ecollab
