trigger:
  branches:
    include:
      - master
  tags:
    include:
      - v*

resources:
- repo: self

stages:
- stage: Deployment
  displayName: Deployment
  jobs:
  - job: Deployment
    displayName: Deployment on integration
    pool:
      vmImage: 'ubuntu-latest'
    steps:
    - task: SSH@0
      inputs:
        sshEndpoint: ecollab-integration
        runOptions: 'commands'
        commands: |
          ECOLLAB_RELEASE=`sudo helm list | awk /ecollab/'{ print $1 }'`
          sudo helm repo update
          sudo helm upgrade $ECOLLAB_RELEASE ecollab/ecollab
