# Default values for ecollab.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

imageCredentials:
  registry: rg.fr-par.scw.cloud
  username: nologin
  password: xxx

# 'latest' are not real version number and must be overriden
versions:
  saas: git-3b7a25c
  backend: git-3984998
  frontend: git-3d522a2
  activiti: 7.2.3
  blazegraph: git-bcb3856
  processes: git-9b45881
  # connectors: latest

rootUri: "https://ecollab.cenotelie.fr"
