apiVersion: v1
kind: Secret
metadata:
  name: ecollab-registry
  namespace: default
data:
  .dockerconfigjson: ewogICJhdXRocyI6IHsKICAgICJyZy5mci1wYXIuc2N3LmNsb3VkIjogewogICAgICAiYXV0aCI6ICJibTlzYjJkcGJqb3lNMkU0TURkaE5TMHhaVEF6TFRRd1lqSXRZamsyWmkwd05EQTJZekJrTVRsa016Yz0iCiAgICB9CiAgfSwKICAiSHR0cEhlYWRlcnMiOiB7ICJVc2VyLUFnZW50IjogIkRvY2tlci1DbGllbnQvMTguMDkuMCAobGludXgpIiB9Cn0K
type: kubernetes.io/dockerconfigjson
