apiVersion: v1
kind: ServiceAccount
metadata:
  namespace: default
  name: auto-deployer

---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: default
  name: auto-deployer-role
rules:
- apiGroups: ["", "apps"] # "" indicates the core API group
  resources: ["deployments", "services"]
  verbs: ["get", "list", "create", "update", "patch", "delete"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: auto-deployer-binding
  namespace: default
roleRef:  
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: auto-deployer-role
subjects:
- namespace: default
  kind: ServiceAccount
  name: auto-deployer