kind: Deployment
apiVersion: apps/v1
metadata:
  name: ldap-server
  labels:
    app: ldap-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ldap-server
  template:
    metadata:
      labels:
        app: ldap-server
    spec:
      imagePullSecrets:
      - name: ecollab-registry
      containers:
        - name: ldap-server
          image: "rg.fr-par.scw.cloud/ecollab/ldap:{{ .Values.versions.saas }}"
          env:
            - name: LDAP_ORGANISATION
              value: "cenotelie"
            - name: LDAP_DOMAIN
              value: "cenotelie.org"
            - name: LDAP_ADMIN_PASSWORD
              value: "eCollab"

---
apiVersion: v1
kind: Service
metadata:
  name: ldap-server
spec:
  ports:
    - protocol: TCP
      name: ldap-server1
      port: 389
      targetPort: 389
    - protocol: TCP
      name: ldap-server2
      port: 636
      targetPort: 636
  selector:
    app: ldap-server