kind: Deployment
apiVersion: apps/v1
metadata:
  namespace: default
  name: keycloak-postgres
  labels:
    app: keycloak-postgres

spec:
  replicas: 1
  selector:
    matchLabels:
      app: keycloak-postgres
  template:
    metadata:
      labels:
        app: keycloak-postgres
    spec:
      volumes:
        - name: keycloak-data
          hostPath:
            path: /data/keycloak-pg
      containers:
        - name: keycloak-postgres
          image: postgres:alpine
          ports:
            - name: sql
              containerPort: 5432
          env:
            - name: POSTGRES_USER
              value: "keycloak"
            - name: POSTGRES_PASSWORD
              value: "keycloak"
            - name: POSTGRES_DB
              value: "keycloak"
          volumeMounts:
            - mountPath: "/var/lib/postgresql/data"
              name: keycloak-data

---
apiVersion: v1
kind: Service
metadata:
  name: keycloak-postgres
spec:
  ports:
    - protocol: TCP
      name: sql
      port: 5432
      targetPort: 5432
  selector:
    app: keycloak-postgres

---
kind: Deployment
apiVersion: apps/v1
metadata:
  namespace: default
  name: keycloak
  labels:
    app: keycloak

spec:
  replicas: 1
  selector:
    matchLabels:
      app: keycloak
  template:
    metadata:
      labels:
        app: keycloak
    spec:
      imagePullSecrets:
      - name: ecollab-registry
      containers:
        - name: keycloak
          image: "rg.fr-par.scw.cloud/ecollab/keycloak:{{ .Values.versions.saas }}"
          ports:
            - name: http
              containerPort: 8180
          env:
            - name: DB_VENDOR
              value: "POSTGRES"
            - name: DB_ADDR
              value: "keycloak-postgres"
            - name: DB_DATABASE
              value: "keycloak"
            - name: DB_USER
              value: "keycloak"
            - name: DB_SCHEMA
              value: "public"
            - name: DB_PASSWORD
              value: "keycloak"
            - name: PROXY_ADDRESS_FORWARDING
              value: "true"

---
apiVersion: v1
kind: Service
metadata:
  name: keycloak
spec:
  ports:
    - protocol: TCP
      name: http
      port: 8180
      targetPort: 8180
  selector:
    app: keycloak
