kind: Deployment
apiVersion: apps/v1
metadata:
  name: nginx
  labels:
    app: nginx

spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      imagePullSecrets:
      - name: ecollab-registry
      containers:
        - name: nginx
          image: "rg.fr-par.scw.cloud/ecollab/nginx:{{ .Values.versions.saas }}"
          ports:
            - name: http
              containerPort: 80
          env:
            - name: RESOLVER
              value: "kube-dns.kube-system.svc.cluster.local"

---
apiVersion: v1
kind: Service
metadata:
  name: nginx
spec:
  type: NodePort
  ports:
    - protocol: TCP
      name: http
      port: 80
      targetPort: 80
      nodePort: 30000
  selector:
    app: nginx
