kind: Deployment
apiVersion: apps/v1
metadata:
  name: frontend
  labels:
    app: frontend

spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      imagePullSecrets:
      - name: ecollab-registry
      containers:
        - name: frontend
          image: "rg.fr-par.scw.cloud/ecollab/frontend:{{ .Values.versions.frontend }}"
          ports:
            - name: http
              containerPort: 80

---
apiVersion: v1
kind: Service
metadata:
  name: frontend
spec:
  ports:
    - protocol: TCP
      name: http
      port: 80
      targetPort: 80
  selector:
    app: frontend
