kind: Deployment
apiVersion: apps/v1
metadata:
  namespace: default
  name: zipkin
  labels:
    app: zipkin

spec:
  replicas: 1
  selector:
    matchLabels:
      app: zipkin
  template:
    metadata:
      labels:
        app: zipkin
    spec:
      imagePullSecrets:
      - name: ecollab-registry
      containers:
        - name: nginx
          image: "openzipkin/zipkin:latest"
          ports:
            - name: http
              containerPort: 9411

---
apiVersion: v1
kind: Service
metadata:
  name: zipkin
spec:
  type: NodePort
  ports:
    - protocol: TCP
      name: http
      port: 4211
      targetPort: 4211
  selector:
    app: zipkin
