kind: Deployment
apiVersion: apps/v1
metadata:
  namespace: default
  name: alfresco-postgres
  labels:
    app: alfresco-postgres

spec:
  replicas: 1
  selector:
    matchLabels:
      app: alfresco-postgres
  template:
    metadata:
      labels:
        app: alfresco-postgres
    spec:
      volumes:
        - name: alfresco-data
          hostPath:
            path: /data/alfresco-pg
      containers:
        - name: alfresco-postgres
          image: postgres:12-alpine
          ports:
            - name: sql
              containerPort: 5432
          env:
            - name: POSTGRES_USER
              value: "alfresco"
            - name: POSTGRES_PASSWORD
              value: "alfresco"
            - name: POSTGRES_DB
              value: "alfresco"
          volumeMounts:
            - mountPath: "/var/lib/postgresql/data"
              name: alfresco-data

---
apiVersion: v1
kind: Service
metadata:
  name: alfresco-postgres
spec:
  ports:
    - protocol: TCP
      name: sql
      port: 5432
      targetPort: 5432
  selector:
    app: alfresco-postgres

---
kind: Deployment
apiVersion: apps/v1
metadata:
  namespace: default
  name: solr6
  labels:
    app: solr6

spec:
  replicas: 1
  selector:
    matchLabels:
      app: solr6
  template:
    metadata:
      labels:
        app: solr6
    spec:
      containers:
        - name: solr6
          image: "alfresco/alfresco-search-services:2.0.0"
          ports:
            - name: solr
              containerPort: 8983
          env:
            - name: SOLR_ALFRESCO_HOST
              value: "alfresco.default.svc.cluster.local"
            - name: SOLR_ALFRESCO_PORT
              value: "8080"
            - name: SOLR_SOLR_HOST
              value: "solr6.default.svc.cluster.local"
            - name: SOLR_SOLR_PORT
              value: "8983"
            - name: SOLR_CREATE_ALFRESCO_DEFAULTS
              value: "alfresco,archive"
            - name: ALFRESCO_SECURE_COMMS
              value: "none"
            - name: SOLR_JAVA_MEM
              value: "-Xms2g -Xmx2g"

---
apiVersion: v1
kind: Service
metadata:
  name: solr6
spec:
  ports:
    - protocol: TCP
      name: http
      port: 8983
      targetPort: 8983
  selector:
    app: solr6

---
kind: Deployment
apiVersion: apps/v1
metadata:
  namespace: default
  name: activemq
  labels:
    app: activemq

spec:
  replicas: 1
  selector:
    matchLabels:
      app: activemq
  template:
    metadata:
      labels:
        app: activemq
    spec:
      containers:
        - name: activemq
          image: "alfresco/alfresco-activemq:5.15.8"
          ports:
            - name: webconsole
              containerPort: 8161
            - name: amqp
              containerPort: 5672
            - name: openwire
              containerPort: 61616
            - name: stomp
              containerPort: 61613

---
apiVersion: v1
kind: Service
metadata:
  name: activemq
spec:
  ports:
    - protocol: TCP
      name: webconsole
      port: 8161
      targetPort: 8161
    - protocol: TCP
      name: amqp
      port: 5672
      targetPort: 5672
    - protocol: TCP
      name: openwire
      port: 61616
      targetPort: 61616
    - protocol: TCP
      name: stomp
      port: 61613
      targetPort: 61613
  selector:
    app: activemq

---
kind: Deployment
apiVersion: apps/v1
metadata:
  namespace: default
  name: transform-core-aio
  labels:
    app: transform-core-aio

spec:
  replicas: 1
  selector:
    matchLabels:
      app: transform-core-aio
  template:
    metadata:
      labels:
        app: transform-core-aio
    spec:
      containers:
        - name: transform-core-aio
          image: "alfresco/alfresco-transform-core-aio:2.3.4"
          ports:
            - name: http
              containerPort: 8090
          env:
            - name: JAVA_OPTS
              value: " -Xms256m -Xmx1536m"

---
apiVersion: v1
kind: Service
metadata:
  name: transform-core-aio
spec:
  ports:
    - protocol: TCP
      name: http
      port: 8090
      targetPort: 8090
  selector:
    app: transform-core-aio

---
kind: Deployment
apiVersion: apps/v1
metadata:
  namespace: default
  name: alfresco
  labels:
    app: alfresco

spec:
  replicas: 1
  selector:
    matchLabels:
      app: alfresco
  template:
    metadata:
      labels:
        app: alfresco
    spec:
      containers:
        - name: alfresco
          image: "alfresco/alfresco-content-repository-community:6.2.1-A8"
          ports:
            - name: http
              containerPort: 8080
          env:
            - name: JAVA_OPTS
              value: "-Ddb.driver=org.postgresql.Driver
                -Ddb.username=alfresco
                -Ddb.password=alfresco
                -Ddb.url=jdbc:postgresql://alfresco-postgres.default.svc.cluster.local:5432/alfresco
                -Dsolr.host=solr6.default.svc.cluster.local
                -Dsolr.port=8983
                -Dsolr.secureComms=none
                -Dsolr.base.url=/solr
                -Dindex.subsystem.name=solr6
                -Dshare.host=share.default.svc.cluster.local
                -Dshare.port=8080
                -Dalfresco.host=localhost
                -Dalfresco.port=8080
                -Daos.baseUrlOverwrite=http://localhost:8080/alfresco/aos
                -Dmessaging.broker.url=\"failover:(nio://activemq.default.svc.cluster.local:61616)?timeout=3000&jms.useCompression=true\"
                -Ddeployment.method=HELM_CHART
                -DlocalTransform.core-aio.url=http://transform-core-aio.default.svc.cluster.local:8090/
                -Dalfresco-pdf-renderer.url=http://transform-core-aio.default.svc.cluster.local:8090/
                -Djodconverter.url=http://transform-core-aio.default.svc.cluster.local:8090/
                -Dimg.url=http://transform-core-aio.default.svc.cluster.local:8090/
                -Dtika.url=http://transform-core-aio.default.svc.cluster.local:8090/
                -Dtransform.misc.url=http://transform-core-aio.default.svc.cluster.local:8090/
                -Dcsrf.filter.enabled=false
                -Xms1500m -Xmx1500m"

---
apiVersion: v1
kind: Service
metadata:
  name: alfresco
spec:
  ports:
    - protocol: TCP
      name: http
      port: 8080
      targetPort: 8080
  selector:
    app: alfresco

---
kind: Deployment
apiVersion: apps/v1
metadata:
  namespace: default
  name: alfresco-share
  labels:
    app: alfresco-share

spec:
  replicas: 1
  selector:
    matchLabels:
      app: alfresco-share
  template:
    metadata:
      labels:
        app: alfresco-share
    spec:
      containers:
        - name: alfresco-share
          image: "alfresco/alfresco-share:6.2.1"
          ports:
            - name: http
              containerPort: 8080
          env:
            - name: JAVA_OPTS
              value: "-Xms500m
                      -Xmx500m
                      -Dalfresco.host=alfresco.default.svc.cluster.local
                      -Dalfresco.port=8080
                      -Dalfresco.context=alfresco
                      -Dalfresco.protocol=http"

---
apiVersion: v1
kind: Service
metadata:
  name: alfresco-share
spec:
  ports:
    - protocol: TCP
      name: http
      port: 8080
      targetPort: 8080
  selector:
    app: alfresco-share
